### ISSUE TITLE
result inconsistency 

### ISSUE THREAD

**Issue by baochi0212** [princeton-nlp/c-sts#2]
Dear team, Thanks for impactful work.
I have an issue when trying to reproduce the result in paper, which turns out to be different when I try flan T5 with k2_short/long  for Spearman correlation score (reported in paper) in test set.
Here is example of T5 large in k2_long setting. Can you please help me clarify this problem?
SHORT:
Results via email: (0.13)
![image](https://github.com/princeton-nlp/c-sts/assets/77192945/8306742f-88ed-48f0-b3c5-e4136be0c4d8)
Results in paper: (10.9) 
![image](https://github.com/princeton-nlp/c-sts/assets/77192945/81117dbb-baf6-48b7-98c7-dc81e76d73f1)
LONG:
Results via email (0.13)
![image](https://github.com/princeton-nlp/c-sts/assets/77192945/0a1ccddd-4787-4589-88f9-bdb8b4b09125)
Results in paper: 4.4
Thanks team

**Comment by baochi0212** [comment]
Hope you can help me soon thanks!

**Comment by carlosejimenez** [comment]
Hello Trần,

I apologize for the delay, it's been a busy week.

Are you loading models in fp16 precision? We noticed substantial
improvements when using bf16 or fp32 precision.

Otherwise, do you think you could send me the code/script you're using to
evaluate? Perhaps on a GitHub gist?

Thanks!

**Comment by closji** [comment]
Hello @baochi0212, 

The prior T5 scores reported in the ArXiv version of this paper are incorrect, since they were mistakenly evaluated in half precision.
An updated version of this paper will be released shortly with more accurate numbers. For instance, Flan-T5-XL on K=2 with short instructions gets 0.253 (25.3) Spearman r, and 0.263 (26.3) Spearman r for long instructions, when evaluated in tf32 precision.

We evaluated Flan-T5-Large on the _validation_ split (not test), and find it gets 0.127 (12.7) Spearman r for K=2/SHORT and 0.111 (11.1) Spearman r for K=2/LONG, so your test results are a little bit higher but within the ballpark it seems. Just remember that the reported numbers are the raw correlation coefficients. We multiply by 100 in the paper to improve readability.

**Comment by baochi0212** [comment]
thanks for your reply @carlosejimenez, but when I do ablation study in validation set, there are some cases that scored 5, but I still don't understand, for example:
Sentence 1: Young woman in orange dress about to serve in tennis game, on blue court with green sides. 
Sentence 2: A girl playing tennis wears a gray uniform and holds her black racket behind her. 
Condition: The color of the dress. 
Label: 5
Can you explain ? thanks

**Comment by baochi0212** [comment]
![image](https://github.com/princeton-nlp/c-sts/assets/77192945/6d3a3898-dd2d-451f-8964-34c1dc2f86bb)
and I witness many cases featuring conditions like this case, is it due to annotating quality ?

**Comment by closji** [comment]
As with any crowd-worker derived datasets, there will be some noise and subjectivity. I suspect these cases are simply a result of the annotation process.

**Comment by baochi0212** [comment]
Is test set 100% correct?

**Comment by baochi0212** [comment]
ok seems like your datasets is not **legit**  😂

**Comment by carlosejimenez** [comment]
It's 100% according to the annotation process. Every crowd-sourced dataset will have some noise and subjectivity.
